# Generated by Django 2.2.3 on 2019-07-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meaning', models.TextField()),
                ('reversal', models.TextField()),
                ('card_id', models.IntegerField()),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
    ]
